### ISSUE TITLE
Your git is highlighted in the Listeo discord server 

### ISSUE THREAD

**Issue by ghost** [levimykel/listeo-child#1]
G'day :)
Ya did such a wonderful job on your Listeo website !

As a modo of the Listeo discord server, I shared your git in order to help and inspire devs / amateur devs among our members.
The link to the private discord server is available on the private Facebook group (otherwise, ya can find the link to the FB group on the Listeo doc).
Let me know if ya made your way to the discord, send me a lil' PM (@John nata)

**Comment by levimykel** [comment]
@john29800 Thanks, I'm glad to share and hopefully inspire others. Cheers!
